# Generated by Django 5.0 on 2023-12-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whs_code', models.CharField(max_length=255)),
                ('whs_name', models.CharField(max_length=255)),
                ('locCode', models.CharField(max_length=255)),
                ('locked', models.BooleanField(default=False)),
                ('binActivant', models.BooleanField(default=False)),
                ('Brunchno', models.IntegerField()),
            ],
        ),
    ]
